Dev multi
kirillProkofiev/light-weight-face-anti-spoofing pull request #4
Opened 2020-09-14 10:02 UTC by kirillProkofiev

start cleaning and preparing the code for the OTE.

2020-09-15 10:39 UTC, sovrasov requested changes

2020-09-15 10:39 UTC, sovrasov commented on train.py
> +path_to_config = os.path.join(current_dir, args.config)
The same thing as in other scripts: config can be located anywhere.

2020-09-15 10:39 UTC, sovrasov commented on train.py
> +BEST_ACCURACY, CURRENT_ACCURACY, BEST_AUC, BEST_EER, BEST_ACER = 0, 0, 0, float('inf'), float('inf')
Try to avoid global variables.

2020-09-15 10:39 UTC, sovrasov commented on train.py
> +    spoof_loss.backward(retain_graph=True)
You actually need to call `backward()` only once on the resulting sum of the losses.

2020-09-15 10:39 UTC, sovrasov commented on train.py
> +def init_experiment(config, path_to_config):
Misleading name of the function

2020-09-15 10:39 UTC, sovrasov commented on train.py
> +    global STEP, args, config
To get rid of unclear manipulations with global variables I suggest to create a class for training that will contain training loops, eval methods and `mixup_criterion` function as a method.

2020-09-15 10:39 UTC, sovrasov commented on utils.py
> +    input, target_a, target_b = map(Variable, (input, target_a, target_b))
`Variable` is a class to emphasize tensors that require grad an ancient versions of pytorch. Now it's completely not needed and exists only for backward compatibility.

2020-09-15 10:39 UTC, sovrasov commented on utils.py
> +        # model = mobilenetv2(prob_dropout=config['dropout']['prob_dropout'])
Dead code

2020-09-17 11:39 UTC, sovrasov commented on configs/config.py
> +datasets = dict(LCCFASD_root='/home/prokofiev/pytorch/LCC_FASDnew',
Get rid of hardcoded absolute path within the project

2020-09-17 11:45 UTC, kirillProkofiev commented on configs/config.py
> +datasets = dict(LCCFASD_root='/home/prokofiev/pytorch/LCC_FASDnew',
This is config file. How can I specify path to my folder without explicitly write it?

2020-09-17 11:53 UTC, sovrasov commented on configs/config.py
> +datasets = dict(LCCFASD_root='/home/prokofiev/pytorch/LCC_FASDnew',
This is actually a sample config provided for users. Paths like `/home/vasyan/my_first_pytorch_project` don't provide any useful information for them.

2020-09-18 10:59 UTC, sovrasov commented on demo/demo.py
> +        std = np.array(self.config.img_norm_cfg.std.).reshape(3,1,1)
Why do you need an extra dot here? (`mean.`)

2020-09-18 13:49 UTC, kirillProkofiev commented on demo/demo.py
> +        std = np.array(self.config.img_norm_cfg.std.).reshape(3,1,1)
bug. I will fix this.

2020-09-21 09:57 UTC, sovrasov commented on README.md
> +To train or evaluate on LCC FASD dataset you need to download it (link is available in their paper on [arxive](https://csit.am/2019/proceedings/PRIP/PRIP3.pdf)) and run following script:
arxiv

2020-09-21 09:57 UTC, sovrasov commented on README.md
> +* loss - there are available two possible losses: 'amsoftmax' with 'cos','arcos','cross_enropy' margins and 'soft_triple' with different number of inner classes. For more details about this soft loss
soft triple?

2020-09-23 11:09 UTC, sovrasov commented on README.md
> +For additional parameters you can refer to help adding '--help'. For example, you can specify on which GPU you want to train your model. If for some reasons you want to train on CPU, specify `--devic
What if the devices specified via config and command line are different? I think there should be a rule that defines how to override the config in such case or all the device selection parameters should be located in config only.

2020-10-06 10:05 UTC, sovrasov commented on README.md
> +For training or evaluating on CelebA Spoof dataset you need to download dataset (you can do it from their [official repository](https://github.com/Davidzhangyuanhan/CelebA-Spoof)) and then run follow
from the, run the following script, in the root folder

2020-10-06 10:06 UTC, sovrasov commented on README.md
> +To train or evaluate on LCC FASD dataset you need to download it (link is available in their paper on [arxiv](https://csit.am/2019/proceedings/PRIP/PRIP3.pdf)). Then you need to get the OpenVINO™ fac
link is available in the [original paper]

2020-10-06 10:09 UTC, sovrasov commented on README.md
> +| MN3_large |CelebA-Spoof| 0.998 | 2.26 | 0.69 | 6.92 | 3.8 | 0.13 | 2.93 | [snapshot](https://drive.google.com/drive/u/0/folders/1A6wa3AlrdjyNPkXT81knIzXxR7SAYm1q) |
Access to the folder is restricted

2020-10-06 10:14 UTC, sovrasov commented on README.md
> +To train or evaluate on LCC FASD dataset you need to download it (link is available in their paper on [arxiv](https://csit.am/2019/proceedings/PRIP/PRIP3.pdf)). Then you need to get the OpenVINO™ fac
As far as I remember we decided not to duplicate IR with FD on google drive and instead insert a reference to the [model downloader](https://docs.openvinotoolkit.org/latest/omz_tools_downloader_README.html) tool.

2020-10-06 10:31 UTC, sovrasov commented on README.md
> +2) Import reader object to datasets/database.py file. Substitute `do_nothing` with your object in `external_reader=do_nothing` (35 line).
Inconsistent case of the first letter

2020-10-06 10:31 UTC, sovrasov commented on README.md
> +The script for training and inference uses a configuration file. This is default [configuration file](./configs/config.py). You need to specify paths to datasets. Training pipeline supports following
This  is the default one

2020-10-06 10:31 UTC, sovrasov commented on README.md
> +
Please add also a step of conversion to IR with the model optimizer.

2020-10-07 10:26 UTC, sovrasov commented on README.md
> +You will see the mean difference (L1 metric distance) on the first and second predicted class. If it's 10e-6 or less than it's all good.
then?

2020-10-07 10:35 UTC, sovrasov approved these changes

2020-10-07 10:35 UTC, merged